cmd/handle_http_traffic.go, cmd/root_command.go, cmd/run_service.go, cmd/serve_monitor.go, daemon/api.go, daemon/handle_request.go, daemon/wiretap_service.go, shared/config.go, shared/error.go
ranch is only serving the websocket now, as we need a custom handler for the embedded file system and cannot use the spa config.
=> reworked http endpoint handling

config/paths.go, go.mod, go.sum, ui/src/wiretap.ts
No guarantee the type will be set on an invalid schema, so added a fallback check.
=> Fixing bug with #22

cmd/booted_message.go, cmd/handle_http_traffic.go, cmd/load_specification.go, cmd/print_banner.go, cmd/root_command.go, cmd/run_service.go, cmd/serve_monitor.go, config/config_service.go, config/paths.go, config/paths_test.go, controls/controls_service.go, daemon/api.go, daemon/cors_middleware.go, daemon/dto.go, daemon/handle_request.go, daemon/monitor_static.go, daemon/validate.go, daemon/wiretap_broadcast.go, daemon/wiretap_init.go, daemon/wiretap_service.go, daemon/wiretap_utils.go, daemon/wiretap_utils_test.go, report/report_service.go, shared/config.go, shared/error.go, shared/language.go, specs/spec_service.go, wiretap.go
Configure a delay for individual path globs! Global delay is the fallback now, indivdual delays are now configurable.
```yaml
pathDelays:
"/very/slow/path": 7000
"/not/so/slow/path": 2000
"/faster/path": 300
```
Add individual delays in milliseconds for as many paths as required. All path keys are globs and can support wildcards (like `/some/*/path/**`
=> Added new feature ‘pathDelays’

daemon/api.go, daemon/build_request.go, daemon/clone_request.go, daemon/handle_request.go, daemon/wiretap_utils_test.go
This PR adds the ability to have a base path to the api url for example `--url http://localhost:5001/api/v1`
=> apply basePath to api request

cmd/root_command.go, cmd/serve_monitor.go, daemon/templates/socket-include.html, shared/config.go, ui/index.html, ui/src/wiretap.ts
**What**: I have tried to add `-v,--ws`-host as an optional configuration option to provide the host of the remote server where wiretap is running. 
**Why**: I want to deploy wiretap on a server and allow my team to access it from a there, which is not working because monitor tries to connect to ws backend at _localhost:<ws-port>_, host is hardcoded in the code at the moment. And cannot be configured.
**Running**
Use either of the following commands to try it out:
`go run wiretap.go -u https://somewhereoutthere.com --ws-host www.websocketHost.com`
or
`go run wiretap.go -u https://somewhereoutthere.com --v www.websocketHost.com`
=> enhance: add config support to provide ws-host param

go.mod, go.sum, ui/src/components/controls/controls.css.ts, ui/src/components/controls/controls.ts, ui/src/components/transaction/transaction-container.ts, ui/yarn.lock
Now validates `http` and `apiKey` security for requests. No breaking changes just more validation!
=> Updated latest libopenapi-validator

.gitignore, daemon/build_request.go, daemon/handle_mock.go, daemon/handle_request.go, go.mod, go.sum, mock/mock_engine_test.go, ui/index.html
Headers need to be handled as a slice of strings, as headers can be duplicated in the HTTP spec.
=> Fixed multi header handling by adapting model to actually be a slice

cmd/root_command.go, config/paths.go, config/paths_test.go, daemon/api.go, shared/config.go, ui/index.html
This MR adds support for:
- An option (ignoreRedirect - list of path) to ignore redirects on certain paths. 
- A second option (redirectAllowList), which configures allowing redirect even if the path matches a path defined in ignoreRedirects
All options here support globbing
=> Add Redirect Ignore List and Redirect Allow List

mock/mock_engine.go, mock/mock_engine_test.go
I've been delighted by `wiretap.` 
As I've used it, I've often wished it could easily mock negative cases that are traditionally hard to test in services which are meant to not fail.
With a small change here to the mock server's algorithm for deciding selection of a mock response, we can unlock even more value from wiretap by mocking negative cases.
=> Provide more developer value via preferred header

cmd/handle_http_traffic.go, cmd/root_command.go, daemon/handle_request.go, daemon/wiretap_service.go, shared/config.go
This MR aims to add support for proxying websockets to wiretap.
It skips validation on this endpoint as OpenAPI does not really support websocket specification.
I am not the most familiar with gorilla/websocket so I may have missed something.
=> Added support for Websockets

cmd/root_command.go, config/paths.go, config/paths_test.go, daemon/handle_request.go, daemon/validate.go, go.mod, shared/config.go
This MR adds two configuration options:
- `ignoreValidation`
- `validationAllowList`
Paths that match ignoreValidation will not have wiretap validation run on them, unless they match the validationAllowList.
=> Add Request Validation Filtering

daemon/handle_mock.go
This pull request introduces a safeguard in the event that the `mock` object is nil. This will fix cases where the response is HTTP 204 with no response body.
```
http: panic serving [::1]:54949: http: request method or response status code does not allow body
goroutine 5165 [running]:
net/http.(*conn).serve.func1()
/usr/local/go/src/net/http/server.go:1898 +0x118
panic({0x104071000?, 0x1400031fde0?})
/usr/local/go/src/runtime/panic.go:770 +0xf0
github.com/pb33f/wiretap/daemon.(*WiretapService).handleMockRequest(0x140010aa820, 0x140015fc240, 0x140003a0908, 0x140014d4fc0)
/Users/martinsirbe/dev/go/src/github.com/pb33f/wiretap/daemon/handle_mock.go:95 +0xf3c
github.com/pb33f/wiretap/daemon.(*WiretapService).handleHttpRequest(0x140010aa820, 0x140015fc240) …
```
=> Check if mock is not nil before writing response

cmd/booted_message.go, cmd/root_command.go, daemon/handle_request.go, go.mod, go.sum, shared/config.go
Added a --strict-redirect-location option; if enabled wiretap will rewrite all `Location` header hosts to wiretap's api gateway host
=> Added a --strict-redirect-location option

mock/mock_engine.go, mock/mock_engine_test.go
This PR updates the mock response handling logic to correctly recognize and process HTTP 204 status codes without expecting a response body.
Currently, the mock server handles mocked responses for requests that are expected to return an HTTP 204 status code. The core issue lies in the service treating HTTP 204 responses as if they should return content.
For more details, please see the `TestNewMockEngine_UseExamples_204_Response` test case.
=> Fix Mock Handling for 204 Success Responses

cmd/root_command.go, config/paths.go, shared/config.go
Wiretap just blindly rewrites paths that match any configuration.
Some (poorly written) APIs don't necessarily want to rewrite everything under a specific resource location.
The current way to do this is to add a dummy path rewrite that takes precedence. This is kind of hacky and also doesn't jump over target rewriting. 
This MR adds first party support for ignoring path rewriting on these unintended endpoints.
=> Added global and local ignore path rewriting support to path configurations

cmd/root_command.go
was throwing a panic when no config was used. A recent addition to the configuration, needs a nil check when booting.
=> Added nill check for path configuration options. Fixes panic thrown by root.

config/paths.go, config/paths_test.go
There are multiple possible formatting possibilities for header values.
This MR ensures that a variety of header formatting methods are supported for the RewriteId feature.
=> OPENAPI: the rewrite header key formatting is wrong in code

cmd/root_command.go
Circular references are no reason to fail running wiretap. Warnings are printed if there are errors, but the model is loaded.
=> Addressed issue #132

mock/mock_engine.go, mock/mock_engine_test.go
Noticed that the `Accept` header was not considered when wiretap was selecting from possible mock responses, while the `Content-Type` header was. 
This change makes wiretap consider the client's Accept header (as a very basic form of mocking [content negotation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation)) when deciding what if any example should be used for a mock response.
=> fix: also consider Accept header in addition to Content-Type 

.github/workflows/publish.yaml, Dockerfile
- Adds muti-platform support to go commands
- Changed to three stage build so ui and go build are mostly parallel and final stage does not have any of the files used for building.
- Tweaked pubish github workflow to minimally publish containers for two platforms, `linux/amd64` and `linux/arm64`
=> Update docker build

static-mock/README.md
The static mock documentation did not reflect the feature's expectations and behaviour explained in issue #153 .
The documentation has been updated to:
- include a valid command line as the first example of how to use the feature (i.e. added `-u` parameter)
- fix an invalid example JSON document (get-test-mock.json), which had a trailing comma where it shouldn't have been. 
- extended the example to include the wiretap and curl commands to test the example, added the expected response JSON document, and adjusted the directory structure to be relative to whereever the user is running the command.
Hopefully this is enough of a change that users can have a successful first test of the feature purely by following the steps laid out in the example.
CC @akash4393
=> Static mock docs updated to reflect usage and include a complete working example

static-mock/handle_static_mock_request.go
`getBodyFromHttpRequest` method in `static-mock/handle_static_mock_request.go` file was reading the body and then downstream consumers of request were unable to access the body object.
Updated logic to restore body so that downstream consumers can read it.
=> Restore body after read so downstream consumers can access it again
