pb33f/wiretap

- .gitignore
- cmd/root_command.go
Adding a .gitignore file to ignore UI dist, node modules and the main built binary.
> Fixes redirectURL arg with a specific port duplicating the port number on redirect calls

- npm-install/config.js
- npm-install/postinstall.js
- package-lock.json
- package.json
docker is now working, now to get NPM and packages working.
> Test release

- .github/workflows/publish.yaml
man, there has to be a better way to test this.
> Lets do another release! Hopefully docker will be nice.

- go.mod
- go.sum
> updated to latest libopenapi-validator

- ui/index.html
- ui/src/components/controls/filters.component.ts
- ui/src/components/divider.css.ts
- ui/src/components/transaction/spec_controls.css.ts
- ui/src/components/transaction/spec_controls.ts
- ui/src/components/transaction/transaction-container.css.ts
- ui/src/components/transaction/transaction-container.ts
- ui/src/components/transaction/transaction-item.css.ts
- ui/src/components/transaction/transaction-item.ts
- ui/src/components/transaction/transaction-view.css.ts
- ui/src/components/transaction/transaction-view.ts
- ui/src/components/violation/violation.ts
- ui/src/css/pb33f.css
- ui/src/index.ts
- ui/src/model/constants.ts
- ui/src/model/events.ts
- ui/src/model/extract_content_type.ts
- ui/src/model/http_transaction.ts
- ui/src/model/link_cache.ts
- ui/src/wiretap.ts
- ui/src/workers/link_cache_worker.ts
chain requests together using query parameters!
> chain feature added to filters.

- README.md
> Add CLI flags to readme

- README.md
- cmd/root_command.go
- config/paths_test.go
- daemon/api.go
- daemon/dto.go
- daemon/handle_request.go
- daemon/wiretap_utils.go
- shared/config.go
- shared/language.go
- ui/src/components/transaction/request-body.ts
- ui/src/model/http_transaction.ts
Cleaned up regex handling for case sensitivity (had to remove viper) and also added query param to all rewrites.
> Added new header drop feature

- README.md
- cmd/root_command.go
- daemon/handle_request.go
- shared/config.go
- ui/src/model/http_transaction.ts
If all my calculations are correct, this should be enough to get up and running with an MVP.
> Static paths can now be configured, along with static index.html

- cmd/run_service.go
- daemon/handle_request.go
- daemon/monitor_static.go
- daemon/templates/socket-include.html
- daemon/wiretap_init.go
- daemon/wiretap_service.go
- daemon/wiretap_utils_test.go
- ui/src/model/constants.ts
- ui/src/wiretap.ts
Any request that comes in, reload!
> Added static file monitoring and auto-reload.

- daemon/handle_request.go
> Fixed drop headers config option crashing application

- cmd/root_command.go
- config/paths.go
- daemon/handle_request.go
- daemon/wiretap_utils.go
- shared/config.go
- wiretap.go
inject headers now and configure basic auth easily.
> Added new variables feature for configuration and header controls

- bin/wiretap.js
- package.json
> Fixing a stupid mistake with npm again.

- go.mod
- go.sum
updated `libopenapi` and `libopenapi-validator`
> updated dependencies

- ui/src/components/controls/controls.ts
- ui/src/components/kv-view/kv-view.ts
- ui/src/components/transaction/transaction-container.ts
- ui/src/wiretap.ts
UI glitches between versions should be cleared.
> Fixed a few bugs with state-resetting, a forced page rebuild works well.

- go.mod
- go.sum
> Updated `libopenapi-validator`

- ui/src/wiretap.ts
I deleted some code I should not had. 
Statis analysis is not to be trusted.
> Fixed major issue with dead code in the UI.

- cmd/booted_message.go
I forgot to tag the previous PR.
> need a new build.

- ui/src/wiretap.ts
fixes https://github.com/pb33f/wiretap/issues/46
**Before:**
**After:**
> fix: glitch on % display on wiretap ui

- go.mod
- go.sum
no new features, just a more compatible libopenapi
> updated libopenapi

- go.mod
- go.sum
fixed various glitches in the stack.
> bumped deps on libopenapi and validator

- go.mod
- go.sum
- mock/mock_engine.go
- mock/mock_engine_test.go
- ui/yarn.lock
And pulled in latest validator with changes in place.
Should resolve #71 and #69
> updated to libopenapi 0.14

- ui/index.html
I accidentally committed some dev env code that should not have ended up in mainline. This MR fixes that.
> previous MR accidentally committed dev env setup for port, host, tls
